const ANALYSIS_INSTRUCTION = `Before providing your final summary, wrap your analysis in <analysis> tags to organize your thoughts and ensure you've covered all necessary points. In your analysis:

1. Chronologically walk through the conversation. For each exchange identify:
   - The user's explicit requests and intents
   - Your approach to addressing those requests
   - Key decisions, concepts, and patterns
   - Important details (names, values, references, file paths, specifics)
   - Any feedback the user gave, especially corrections or preferences
2. Trace the arc of the conversation - how did the user's questions evolve? What direction were they heading?
3. Double-check for completeness and accuracy before writing your summary.`;

const BASE_PROMPT = `Your task is to create a detailed summary of the conversation so far, paying close attention to the user's explicit requests and your previous actions.
This summary should be thorough in capturing context, decisions, and details essential for continuing the conversation seamlessly, as if the break never happened.

${ANALYSIS_INSTRUCTION}

Your summary should include the following sections:

1. Conversational Tone and Style: Describe the overall feel of the conversation - formal, casual, technical, playful, etc. Include the user's communication style (direct questions, tangential exploration, meta-analytical, etc.) and any implied expectations about how you should respond.

2. Key Concepts and Question Arc:
   - List all important concepts, topics, facts, decisions, file paths, and context established during the conversation.
   - Then trace the question progression: what did the user ask about in order, and what did you focus on in each response? Show the arc, not just the facts - the progression matters for continuity.

3. Problem Solving: Document what was attempted, what worked, what didn't, and any ongoing efforts. Include specifics about approaches tried and their outcomes.

4. All User Messages: List ALL user messages that are not tool results. These are critical for understanding the user's voice, feedback, and evolving intent. Include them verbatim or near-verbatim.

5. Pending Tasks and Implicit Threads:
   - Explicit: tasks that were requested but not yet completed.
   - Implicit: what the user seems interested in based on their questioning pattern, and natural next steps based on the conversation's trajectory.

6. Last Exchange and Current Work:
   - Last user message: [exact quote]
   - Your last response focused on: [summary]
   - Implied next direction: [what the user seems to be leading toward]
   - State: any relevant file paths, values, or context needed to resume`;

export function getCompactPrompt(instructions?: string): string {
  let prompt = BASE_PROMPT;

  if (instructions && instructions.trim() !== "") {
    prompt += `\n\nAdditional Instructions:\n${instructions}`;
  }

  return prompt;
}

export function formatCompactSummary(raw: string): string {
  let result = raw;

  result = result.replace(/<analysis>[\s\S]*?<\/analysis>/, "");

  const summaryMatch = result.match(/<summary>([\s\S]*?)<\/summary>/);
  if (summaryMatch) {
    const content = summaryMatch[1] ?? "";
    result = result.replace(
      /<summary>[\s\S]*?<\/summary>/,
      `Summary:\n${content.trim()}`,
    );
  }

  result = result.replace(/\n\n+/g, "\n\n");

  return result.trim();
}

export function getCompactUserSummaryMessage(summary: string): string {
  return `This is an automated context compaction generated by the Bud system (not a user message). The summary below covers the earlier portion of this conversation which has been compressed to free up context space.

${summary}

Continue the conversation from where it left off. Resume directly; do not acknowledge the summary or the compaction, do not recap what was happening, do not preface with "I'll continue" or similar. Match the conversational tone described above and pick up as if the break never happened.`;
}
